# 03 Error Analysis

## Purpose

This notebook performs syllable-level error diagnostics for a selected `my-ph` experiment. It classifies errors into ambiguity, OOV, missing-reference, and over-generalization categories.

In [1]:
from pathlib import Path
import subprocess, re, shutil, os, difflib

BASE_DIR = Path('/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein')
G2P_DIR = BASE_DIR / 'g2p-par'
SGM_DIR = G2P_DIR / 'sgm'
MOSES_SRC_DIR = Path('/home/kyalkalay/tools/mosesdecoder')
MOSES_SCRIPT_DIR = MOSES_SRC_DIR / 'scripts'
MOSES_BIN_DIR = MOSES_SRC_DIR / 'bin'
EXPERIMENT_PERL = MOSES_SCRIPT_DIR / 'ems' / 'experiment.perl'
MTEVAL = MOSES_SCRIPT_DIR / 'generic' / 'mteval-v13a.pl'

# The original assignment experiment directory.
ORIGINAL_EXP_DIR = BASE_DIR / 'pbsmt-big-normalize'
ORIGINAL_TEMPLATE = ORIGINAL_EXP_DIR / 'config.baseline'
ORIGINAL_BASELINE_DIR = ORIGINAL_EXP_DIR / 'baseline'

# New clean experiment directory.
EXP_DIR = BASE_DIR / 'pbsmt_original_clean_experiments'

print('BASE_DIR:', BASE_DIR)
print('G2P_DIR:', G2P_DIR)
print('SGM_DIR:', SGM_DIR)
print('Original template:', ORIGINAL_TEMPLATE, ORIGINAL_TEMPLATE.exists())
print('Clean experiment dir:', EXP_DIR)

BASE_DIR: /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein
G2P_DIR: /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par
SGM_DIR: /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/sgm
Original template: /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt-big-normalize/config.baseline True
Clean experiment dir: /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments

In [2]:
import pandas as pd
from collections import defaultdict, Counter

EXPERIMENT = 'pbsmt_5gram_main'
DIRECTION = 'my-ph'
EVAL_DIR = EXP_DIR / EXPERIMENT / DIRECTION / 'evaluation'

file_train_src = G2P_DIR / 'train_clean.my'
file_train_trg = G2P_DIR / 'train_clean.ph'
file_test_src  = EVAL_DIR / 'test.input.txt.1'
file_test_out  = EVAL_DIR / 'test.output.1'
file_test_ref  = EVAL_DIR / 'test.reference.txt.1'

for p in [file_train_src, file_train_trg, file_test_src, file_test_out, file_test_ref]:
    print(p, p.exists())

/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/train_clean.my True
/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/train_clean.ph True
/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_main/my-ph/evaluation/test.input.txt.1 True
/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_main/my-ph/evaluation/test.output.1 True
/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_main/my-ph/evaluation/test.reference.txt.1 True

In [3]:
def clean_moses_output(line):
    return ' '.join(re.sub(r'\|\d+-\d+\|', '', line).split()).strip()

train_counts = defaultdict(Counter)
with file_train_src.open(encoding='utf-8') as f_src, file_train_trg.open(encoding='utf-8') as f_trg:
    for src_line, trg_line in zip(f_src, f_trg):
        s_tokens = src_line.strip().split()
        t_tokens = trg_line.strip().split()
        if len(s_tokens) == len(t_tokens):
            for s, t in zip(s_tokens, t_tokens):
                train_counts[s][t] += 1

raw_errors = []
with file_test_src.open(encoding='utf-8') as f_src, file_test_out.open(encoding='utf-8') as f_out, file_test_ref.open(encoding='utf-8') as f_ref:
    for src, out, ref in zip(f_src, f_out, f_ref):
        src_tokens = src.strip().split()
        ref_tokens = ref.strip().split()
        out_line = out.strip()
        tagged = re.findall(r'([^|]+?)\|(\d+)-(\d+)\|', out_line)
        covered = set()
        if tagged:
            for pred_phrase, start_s, end_s in tagged:
                start, end = int(start_s), int(end_s)
                pred = ' '.join(pred_phrase.split()).strip()
                if end < len(ref_tokens):
                    src_chunk = ' '.join(src_tokens[start:end+1])
                    ref_chunk = ' '.join(ref_tokens[start:end+1])
                    covered.update(range(start, end+1))
                    if pred != ref_chunk:
                        raw_errors.append((src_chunk, pred, ref_chunk))
            for i in range(min(len(src_tokens), len(ref_tokens))):
                if i not in covered:
                    raw_errors.append((src_tokens[i], '[DELETED]', ref_tokens[i]))
        else:
            pred_tokens = clean_moses_output(out_line).split()
            for s, pred, r in zip(src_tokens, pred_tokens, ref_tokens):
                if pred != r:
                    raw_errors.append((s, pred, r))

records = []
for src_chunk, pred, ref in raw_errors:
    tr = train_counts.get(src_chunk, Counter())
    total = sum(tr.values())
    pred_freq = tr.get(pred, 0)
    ref_freq = tr.get(ref, 0)
    if total == 0:
        cause = 'Out of Vocabulary (OOV)'
    elif pred_freq > 0 and ref_freq > 0:
        cause = 'Train Data Ambiguity (Both Exist)'
    elif ref_freq == 0 and pred_freq > 0:
        cause = 'Reference Missing from Training Token'
    elif pred_freq == 0 and ref_freq > 0:
        cause = 'Decoder Hallucination / Over-generalization'
    else:
        cause = 'Unclassified Structural Swap'
    records.append({
        'Source_Syllable': src_chunk,
        'Moses_Output': pred,
        'True_Reference': ref,
        'Train_Total_Seen': total,
        'Train_Prob_Pred': round(pred_freq/total, 3) if total else 0.0,
        'Train_Prob_Ref': round(ref_freq/total, 3) if total else 0.0,
        'Root_Cause': cause,
    })

df_errors = pd.DataFrame(records)
summary = df_errors['Root_Cause'].value_counts().rename_axis('Root_Cause').reset_index(name='Count') if not df_errors.empty else pd.DataFrame()
if not summary.empty:
    summary['Percentage'] = (summary['Count'] / summary['Count'].sum() * 100).round(2)
leaderboard = df_errors.groupby(['Source_Syllable','Moses_Output','True_Reference','Root_Cause']).size().reset_index(name='Error_Count').sort_values('Error_Count', ascending=False) if not df_errors.empty else pd.DataFrame()

df_errors.to_csv(f'error_details_{EXPERIMENT}_{DIRECTION}.csv', index=False)
summary.to_csv(f'error_summary_{EXPERIMENT}_{DIRECTION}.csv', index=False)
leaderboard.to_csv(f'error_leaderboard_{EXPERIMENT}_{DIRECTION}.csv', index=False)
summary

                                    Root_Cause  Count  Percentage
0            Train Data Ambiguity (Both Exist)    856       72.91
1                      Out of Vocabulary (OOV)    232       19.76
2        Reference Missing from Training Token     85        7.24
3  Decoder Hallucination / Over-generalization      1        0.09

In [4]:
leaderboard.head(50)

,Source_Syllable,Moses_Output,True_Reference,Root_Cause,Error_Count
131,ခံ,khan,gan,Train Data Ambiguity (Both Exist),12
585,မ,ma-,ma.,Train Data Ambiguity (Both Exist),10
162,ခြေ,chei,chi,Train Data Ambiguity (Both Exist),8
688,ဝါး,wa:,wa-,Train Data Ambiguity (Both Exist),8
46,ကျ,kya.,gya.,Train Data Ambiguity (Both Exist),7
492,ပေါက်,bau',pau',Train Data Ambiguity (Both Exist),7
78,ကြား,gya:,kya:,Train Data Ambiguity (Both Exist),7
1,က,ka-,ga-,Train Data Ambiguity (Both Exist),7
219,စား,za:,sa:,Train Data Ambiguity (Both Exist),7
363,တောင်,taun,daun,Train Data Ambiguity (Both Exist),6
476,ပိုး,pou:,bou:,Train Data Ambiguity (Both Exist),6
274,ဆိုး,hsou:,zou:,Train Data Ambiguity (Both Exist),6
85,ကြီး,gyi:,kyi:,Train Data Ambiguity (Both Exist),6
321,တင်,tin,din,Train Data Ambiguity (Both Exist),6
742,သွား,dhwa:,thwa:,Train Data Ambiguity (Both Exist),6
719,သား,dha:,tha:,Train Data Ambiguity (Both Exist),6
549,ဖက်,hpe',be',Train Data Ambiguity (Both Exist),5
285,ဆေး,hsei:,zei:,Train Data Ambiguity (Both Exist),5
236,စောင်,saun,zaun,Train Data Ambiguity (Both Exist),5
294,ဆွဲ,hswe:,zwe:,Train Data Ambiguity (Both Exist),5
354,တုတ်,tou',dou',Train Data Ambiguity (Both Exist),5
30,ကုန်,koun,goun,Train Data Ambiguity (Both Exist),5
2,က,ka-,ka.,Train Data Ambiguity (Both Exist),5
242,စေ့,zei.,sei.,Train Data Ambiguity (Both Exist),5
208,စဉ်,zin,sin,Train Data Ambiguity (Both Exist),5
172,ခွက်,khwe',gwe',Train Data Ambiguity (Both Exist),5
312,တ,ta-,da-,Train Data Ambiguity (Both Exist),4
369,တံ,dan,tan,Train Data Ambiguity (Both Exist),4
147,ချို,chou,gyou,Train Data Ambiguity (Both Exist),4
230,စီး,zi:,si:,Train Data Ambiguity (Both Exist),4
401,ထောင်,htaun,daun,Train Data Ambiguity (Both Exist),4
357,တူ,du,tu,Train Data Ambiguity (Both Exist),4
344,တိုက်,tai',dai',Train Data Ambiguity (Both Exist),4
521,ပြန်,pjan,bjan,Train Data Ambiguity (Both Exist),4
730,သေ,dhei,thei,Train Data Ambiguity (Both Exist),4
28,ကိုင်,kain,gain,Train Data Ambiguity (Both Exist),4
41,ကောင်း,kaun:,gaun:,Train Data Ambiguity (Both Exist),4
489,ပူ,pu,bu,Train Data Ambiguity (Both Exist),4
0,က,ga-,ka-,Train Data Ambiguity (Both Exist),4
170,ခြောက်,chau',gyau',Train Data Ambiguity (Both Exist),4
152,ချုပ်,gyou',chou',Train Data Ambiguity (Both Exist),4
205,စင်,zin,sin,Train Data Ambiguity (Both Exist),4
438,နှင့်,nhin.,ne.,Train Data Ambiguity (Both Exist),4
54,ကျယ်,kye,gye,Train Data Ambiguity (Both Exist),4
425,နည်း,ni:,ne:,Train Data Ambiguity (Both Exist),4
429,နား,na:,na-,Train Data Ambiguity (Both Exist),4
693,သ,tha-,dha-,Train Data Ambiguity (Both Exist),3
651,ရေ,jei,rei,Train Data Ambiguity (Both Exist),3
748,အ,a-,a,Train Data Ambiguity (Both Exist),3
17,ကပ်,ka',ga',Train Data Ambiguity (Both Exist),3

In [5]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep 'ခံ'

အ ခံ ဆေး	a- khan |0-1| zei: |2-2| 	a- khan hsei:
အာ မ ခံ ပစ် စည်း	a ma. gan |0-2| pji' si: |3-4| 	a ma. gan pji' si:
မိုး ရေ ခံ သင် ကန်း	mou: |0-0| jei |1-1| gan |2-2| thin gan: |3-4| 	mou: jei gan thin gan:
ခံ တပ်	gan |0-0| ta' |1-1| 	khan da'
သီ ချင်း ခံ	tha- chin: |0-1| khan |2-2| 	tha- chin: gan
ကြံ့ ကြံ့ ခံ	kyan. |0-0| kyan. |1-1| khan |2-2| 	kyan. gyan. khan
တာ ဝန် ခံ	ta |0-0| wun |1-1| khan |2-2| 	ta win gan
ဆွမ်း ခံ	hsun: |0-0| khan |1-1| 	hswan: khan
ခေါင်း ခံ	gaun: |0-0| khan |1-1| 	gaun: khan
ပလ် လင် ခံ	pa- lin |0-1| khan |2-2| 	pa- lin khan
ခံ ချိ	khan gyi. |0-1| 	khan chi.
စ ကား ပလ် လင် ခံ	za- ga- |0-1| pa- lin |2-3| khan |4-4| 	za- ga: pa- lin khan
ခြင် ခံ	chin |0-0| khan |1-1| 	chin gan
အ ခွင့် ထူး ခံ	a- |0-0| khwin. |1-1| du: |2-2| khan |3-3| 	a- khwin. du: gan
အ တိုင် ပင် ခံ	a- |0-0| tain |1-1| pin |2-2| khan |3-3| 	a- tain bin gan
ဂုဏ် ခံ	goun |0-0| khan |1-1| 	goun khan
အ ရှုံး ခံ	a- |0-0| shoun: |1-1| khan |2-2| 	a- shoun: khan
က တိ ခံ ဝန် ချက်	ga- di. |0-1| khan |2-2| wun |3-3| gye' |4-4| 	ga- di. khan wun gye'
ခံ တက်	ga- de' |0-1| 	kha- de'
နာ လို ခံ ခက်	na |0-0| lou |1-1| khan |2-2| khe' |3-3| 	na lou khan khe'
လည် စင်း ခံ	le |0-0| zin: |1-1| khan |2-2| 	le sin: khan
ခံ မြို့	khan |0-0| mjou. |1-1| 	khan mjou.
အ ယူ ခံ	a- ju |0-1| gan |2-2| 	a- ju khan
လေ ညင်း ခံ	lei |0-0| njin: |1-1| khan |2-2| 	lei njin: khan
နယ် ခံ	ne |0-0| khan |1-1| 	ne gan
အ ခံ့ သား	a- |0-0| khan. |1-1| dha: |2-2| 	a- khan. dha:
ဓာတ် ခံ	da' |0-0| khan |1-1| 	da' khan
မီး အာ မ ခံ	mi: |0-0| a ma. gan |1-3| 	mi: a ma. gan
ဆက် ခံ	hse' |0-0| khan |1-1| 	hse' khan
ပြန် တမ်း ခံ	pjan dan: |0-1| khan |2-2| 	pjan dan: khan
မြေ ခံ	mjei |0-0| khan |1-1| 	mjei gan
မြို့ ခံ	mjou. |0-0| khan |1-1| 	mjou. gan
ဆွမ်း ခံ ပင့်	hsun: |0-0| khan |1-1| pin. |2-2| 	hsun: gan pin.
အ ရိုး ခံ	a- |0-0| jou: |1-1| khan |2-2| 	a- jou: gan
ခံ့ ညား	khan. |0-0| nja: |1-1| 	khan. nja:
ဒိုင် ခံ	dain |0-0| khan |1-1| 	dain khan
နေ ပူ ခံ သီး	nei |0-0| bu |1-1| khan |2-2| dhi: |3-3| 	nei pu gan dhi:
နာ မည် ခံ	nan me |0-1| khan |2-2| 	na mji gan
ခံ တွင်း ရှင်း	ga- dwin: |0-1| shin: |2-2| 	ga- dwin: shin:
လိုင် စင် ခံ	lain |0-0| sin |1-1| khan |2-2| 	lain sin khan

In [6]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep ' မ '

ဥ မ ကွဲ သိုက် မ ပျက်	u. |0-0| ma- |1-1| kwe: |2-2| thai' |3-3| ma- |4-4| pje' |5-5| 	u. ma- kwe: thai' ma- pje'
မ ဆုတ် မ ဆိုင်း	ma- |0-0| hsou' |1-1| ma- |2-2| hsain: |3-3| 	ma- hsou' ma- hsain:
အ လိုက် ကမ်း ဆိုး မ သိ	a- |0-0| lai' |1-1| kan: |2-2| hsou: |3-3| ma- thi. |4-5| 	a- lai' kan: zou: ma- thi.
အာ မ ခံ ပစ် စည်း	a ma. gan |0-2| pji' si: |3-4| 	a ma. gan pji' si:
ယင် မ မဲ ရိုင်း	jin |0-0| ma- |1-1| me: |2-2| jain: |3-3| 	jin ma. me: jain:
အင် ဂ သ မ ဥစ် စာ	in: ga- |0-1| tha- ma. |2-3| ou' sa |4-5| 	in ga. tha- ma. ou' sa
သား ကြီး မ ယား ကြီး	tha: |0-0| gyi: |1-1| ma- ja: |2-3| gyi: |4-4| 	tha: gyi: ma- ja: gyi:
ကင်း မ လက် မည်း	kin: |0-0| ma- |1-1| le' |2-2| me: |3-3| 	kin: ma. le' me:
မိန်း မ မှု	mein: ma- |0-1| mhu. |2-2| 	mein: ma. mhu.
သ မ ပိုင်း	tha- ma. |0-1| bain: |2-2| 	tha- ma. bain:
သက် မ ချ	the' |0-0| ma- |1-1| cha. |2-2| 	the' ma. cha.
မ ရှု မ လှ	ma- |0-0| shu. |1-1| ma- |2-2| lha. |3-3| 	ma- shu. ma- lha.
အန်း မ ရ	an: |0-0| ma- ja. |1-2| 	an: ma- ja.
ဝမ်း မ လုံ	wan: |0-0| ma- |1-1| loun |2-2| 	wan: ma- loun
စိတ် မ ရှိ ပါ နှင့်	sei' |0-0| ma- shi. |1-2| ba |3-3| nhin. |4-4| 	sei' ma- shi. ba ne.
နေ မ ထိ ထိုင် မ ထိ	nei |0-0| ma- |1-1| hti. |2-2| htain |3-3| ma- |4-4| hti. |5-5| 	nei ma- hti. htain ma- hti.
စမ် မ ခန်း	sa- ma- |0-1| khan: |2-2| 	sa- ma- khan:
ဓမ် မ ဝါ ဒီ	da- ma. |0-1| wa di |2-3| 	da- ma. wa di
ပတ် မ လုံး စုံ	pa' |0-0| ma- |1-1| loun: |2-2| zoun |3-3| 	pa' ma. loun: zoun
အ ကဲ မ ရ	a- |0-0| ke: |1-1| ma- ja. |2-3| 	a- ke: ma- ja.
ခြေ မ ကိုင် မိ လက် မ ကိုင် မိ ဖြစ်	chei |0-0| ma- |1-1| kain |2-2| mi. |3-3| le' |4-4| ma- |5-5| kain |6-6| mi. |7-7| hpji' |8-8| 	chi ma- kain mi. le' ma- kain mi. hpji'
ရင် တ မ မ	jin |0-0| ta- |1-1| ma- |2-2| ma. |3-3| 	jin ta- ma. ma.
မျက် နှာ မ ကောင်း	mje' nha- |0-1| ma- kaun: |2-3| 	mje' nha ma- kaun:
အ တု မ ရှိ	a- |0-0| tu. |1-1| ma- shi. |2-3| 	a- tu. ma- shi.
သ မ နိ ရှည်	tha- |0-0| ma- |1-1| ni. |2-2| shei |3-3| 	tha- ma- ni. shei
အ ငမ်း မ ရ	a- |0-0| ngan: |1-1| ma- ja. |2-3| 	a- ngan: ma- ja.
ပု စွန် လက် မ စည်	ba- zun |0-1| le' |2-2| ma- |3-3| si |4-4| 	ba- zun le' ma. si
သု ဝဏ် ဏ သာ မ ဇာတ်	thu. |0-0| wun na. |1-2| tha |3-3| ma- |4-4| za' |5-5| 	thu. wun na. tha ma. za'
အ မှတ် မ ထင်	a- |0-0| mha' |1-1| ma- |2-2| htin |3-3| 	a- mhu. a' ma-
လူ မှန်း မ သိ	lu |0-0| mhan: |1-1| ma- thi. |2-3| 	lu mhan: ma- thi.
မ လှမ်း မ ကမ်း	ma- |0-0| lhan: |1-1| ma- |2-2| kan: |3-3| 	ma- lhan: ma- kan:
အ န မ တဂ် ဂ	a- |0-0| na- |1-1| ma- |2-2| တဂ် |3-3| ga. |4-4| 	a- na. ma- te' ga.
ဝက် မ လွတ်	we' |0-0| ma- |1-1| lu' |2-2| 	we' ma- lu'
ကော် မ ရှင်	ko |0-0| ma- |1-1| shin |2-2| 	ko ma- shin
လူ မှန်း သူ မှန်း မ သိ	lu |0-0| mhan: |1-1| thu |2-2| mhan: |3-3| ma- thi. |4-5| 	lu mhan: thu mhan: ma- thi.
တ ရား မ ကြောင်း	ta- ja- |0-1| ma. |2-2| gyaun: |3-3| 	ta- ja- ma. gyaun:
ပုံ မ ကျ ပန်း မ ကျ	boun |0-0| ma- |1-1| kya. |2-2| pan: |3-3| ma- |4-4| kya. |5-5| 	poun ma- kya. pan: ma- kya.
န ကန်း တစ် လုံး မျှ မ သိ	na- |0-0| gan: |1-1| ta- loun: |2-3| mhja. |4-4| ma- thi. |5-6| 	na. gan: ta- loun: mhja. ma- thi.
အင် မ တိ အင် မ တန်	in |0-0| ma- |1-1| ti. |2-2| in |3-3| ma- tan |4-5| 	in ma- ti. in ma- tan
အိမ်း အည်း မ လုပ်	ein: e: ma- lou' |0-3| 	ein: i: ma- lou'
ဓမ် မ ဒူ တ	da- ma. |0-1| du |2-2| ta. |3-3| 	da- ma. du ta.
မိန်း မ ဉာဏ်	mein: ma- |0-1| njan |2-2| 	mein: ma- njan
ကမ် မ ဇိဒ် ဓိ	ka- ma- |0-1| ဇိဒ် |2-2| di. |3-3| 	ka- ma- zei' di.
နောက် မ ယား	nau' |0-0| ma- ja: |1-2| 	nau' ma- ja:
ရက် မ လျှို	je' |0-0| ma- |1-1| shou |2-2| 	je' ma. shou
မိန်း မ ထိန်း	mein: ma- |0-1| dein: |2-2| 	mein: ma- dein:
မီး အာ မ ခံ	mi: |0-0| a ma. gan |1-3| 	mi: a ma. gan
အ ခဲ မ ကျေ	a- |0-0| khe: |1-1| ma- |2-2| kyei |3-3| 	a- khe: ma- kyei
ဓား မ ဦး ချ မြေ	da- |0-0| ma- |1-1| u: |2-2| cha. |3-3| mjei |4-4| 	da- ma- u: gya. mjei
အ ကြောင်း မ လှ	a- kyaun: |0-1| ma- |2-2| lha. |3-3| 	a- kyaun: ma- lha.
ပ ထ မ ငယ်	pa- hta- |0-1| ma- |2-2| nge |3-3| 	pa- hta- ma- nge
မြေ ဝယ် မ ကျ	mjei |0-0| we |1-1| ma- |2-2| kya. |3-3| 	mjei we ma- kya.
ကံ ကောင်း ထောက် မ လို့	kan |0-0| kaun: |1-1| htau' |2-2| ma- |3-3| lou. |4-4| 	kan gaun: htau' ma. lou.
စ တု မ ဟာ ရာဇ်	sa- tu. |0-1| ma- ha |2-3| ji' |4-4| 	sa- tu. ma- ha ri
နည်း များ မ ဆို	ni: |0-0| mja: |1-1| ma- |2-2| hsou |3-3| 	ne: mja: ma- hsou
အ ခါ သ မ ယ	a- kha |0-1| tha- ma- ja. |2-4| 	a- kha tha- ma- ja.

In [7]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep ' က '

ပက် က လာ	pe' |0-0| ga- |1-1| la |2-2| 	pe' ka- la
ပ က တိ ပ မာ ဏ	ba- ga- di. |0-2| pa- ma |3-4| na. |5-5| 	ba- ga- di. pa- ma na.
စီး က ရက်	si: |0-0| ka- |1-1| re' |2-2| 	si: ka- re'
ပြူး က လူး ပျာ က လာ	pju: |0-0| ka- |1-1| lu: |2-2| bja ga- |3-4| la |5-5| 	pju: ga- lu: pja ga- la
က တိမ်း က ပါး ဖြစ်	ga- dein: ga- |0-2| ba: |3-3| hpji' |4-4| 	ga- dein: ga- ba: hpji'
ပြ က တေ့	pja. |0-0| ka- |1-1| tei. |2-2| 	bja. ga- dei.
သက် ရင်း က တိုး	the' |0-0| jin: |1-1| ga- dou: |2-3| 	the' jin: ga- dou:
က ပျာ က သီ	ga- |0-0| bja |1-1| ka- thi |2-3| 	ga- bja ga- thi
အာ ဝေ ဏိ က ဒုက် ခ	a |0-0| wei |1-1| ni. |2-2| ka. |3-3| dou' kha. |4-5| 	a wei ni. ka. dou' kha.
တ က တဲ မှ ပဲ	da- ga- de: |0-2| mha. |3-3| pe: |4-4| 	da- ga- de: mha. be:
လူ က လေး	lu |0-0| ga- lei: |1-2| 	lu ga- lei:
က ရိ က ထ	ka- |0-0| ri. |1-1| ka- |2-2| hta. |3-3| 	ka- ji. ka- hta.
အ က အ ခုန်	a- |0-0| ka- |1-1| a- |2-2| khoun |3-3| 	a- ka. a- khoun
ဇ န က ဇာတ်	za- na- |0-1| ka. |2-2| za' |3-3| 	za- na- ka za'
အော် တို က ရေ စီ	o |0-0| tou |1-1| ka- |2-2| jei |3-3| si |4-4| 	o tou ka- rei si
ရွှေ စွန် ညို က စား နည်း	shwei |0-0| zun |1-1| njou |2-2| ga- za: |3-4| ni: |5-5| 	shwei sun njou ga- za: ni:
သိုး က လေး	thou: |0-0| ga- lei: |1-2| 	thou: ga- lei:
က နု က မာ	ka- |0-0| nu. |1-1| ka- |2-2| ma |3-3| 	ka- nu. ka- ma
နား က လော	na- |0-0| ga- |1-1| lo: |2-2| 	na: ka- lo:
ကက် က ရု	ke' |0-0| ga- ju. |1-2| 	ke' ka- ru.
သက် က ရာဇ် တက်	the' ka- ji' |0-2| te' |3-3| 	dha- ga- ji' te'
လော က ဝတ်	lo: ka. |0-1| wu' |2-2| 	lo: ka. wu'
တောင် တန် က တိုး	taun |0-0| tan |1-1| ga- dou: |2-3| 	taun dan ga- dou:
ကောင် က လေး	kaun |0-0| ga- lei: |1-2| 	kau nga- lei:
ဗျူ ရို က ရေ စီ	bju rou |0-1| ka- |2-2| jei |3-3| si |4-4| 	bju rou ka- rei si
အ နေ က သင် ချာ	a- |0-0| nei |1-1| ka. |2-2| thin |3-3| cha |4-4| 	a- nei ka. thin cha
စော ဒ က တက်	so: |0-0| da- |1-1| ka. |2-2| te' |3-3| 	so: da- ka. te'
ကြာ က လပ်	kya |0-0| ka- |1-1| la' |2-2| 	kya ka- la'
သ မင် က လေး	tha- min |0-1| ga- lei: |2-3| 	tha- min ga- lei:
က ရိ က ထ များ	ka- |0-0| ri. |1-1| ka- |2-2| hta. |3-3| mja: |4-4| 	ka- ji: ka- hta. mja:
လက် က တော့ တင်	le' |0-0| ga- do. |1-2| tin |3-3| 	le' ga- do. tin
က တောက် က ဆတ် ဖြစ်	ga- dau' |0-1| ga- |2-2| hsa' |3-3| hpji' |4-4| 	ga- dau' ga- hsa' hpji'
လော က ကြောင်း	lo: ka. |0-1| gyaun: |2-2| 	lo: ka. gyaun:
ရုံး ပြင် က နား ရောက်	joun: |0-0| bjin |1-1| ka- |2-2| na: |3-3| jau' |4-4| 	joun: bjin ka- na: jau'
အော် ဒီ က လုံး	o |0-0| di |1-1| ga- |2-2| loun: |3-3| 	o di ka- loun:
ဘ ယာ န က ရ သ	ba- ja |0-1| na. |2-2| ka- |3-3| ra. tha. |4-5| 	ba- ja na- ka. ja. tha.
မြေ က တုတ်	mjei |0-0| ka- |1-1| tou' |2-2| 	mjei ga- dou'
ဈေး က စား	zei: |0-0| ga- za: |1-2| 	zei: ga- za:
နတ် က တော်	na' |0-0| ka- |1-1| do |2-2| 	na' ga- do
သို့ က လောက်	dhou. |0-0| ga- |1-1| lau' |2-2| 	dhou. ga- lau'
ဒီ မို က ရေ စီ	di |0-0| mou |1-1| ka- |2-2| jei |3-3| si |4-4| 	di mou ka- rei si
တက် က ဗေ ဒ	te' |0-0| ka- |1-1| bei da. |2-3| 	te' ka. bei da.
က နက် က ဒဏ်	ka- |0-0| ne' |1-1| ga- |2-2| dan |3-3| 	ka- ne' ga- dan
သက် က လတ်	the' ka- |0-1| la' |2-2| 	dha- ga- la'
ဧ က မုခ် အုန်း	ei ga- mou' |0-2| oun: |3-3| 	ei ga- mou' oun:
ရေ က တော့	jei |0-0| ga- do. |1-2| 	jei ga- do.
တက် က စီး	te' |0-0| ka- |1-1| zi: |2-2| 	te' ga- zi:
ဧ က မူ	ei ga- |0-1| mu |2-2| 	ei ga- mu
က လီ က မာ လုပ်	ka- |0-0| li |1-1| ka- |2-2| ma |3-3| lou' |4-4| 	ka- li ka- ma lou'
သက် က ရာဇ် ရှည်	the' ka- ji' |0-2| shei |3-3| 	dha- ga- ji' shei
က မောက် က မ	ka- |0-0| mau' |1-1| ga- |2-2| ma. |3-3| 	ka- mau' ka- ma-
သင် သ က ရိုက်	thin |0-0| tha- ka. |1-2| jai' |3-3| 	thin tha- ka- rai'
ဧ က ပိုဒ်	ei ga- |0-1| bai' |2-2| 	ei ga- bai'

In [8]:
leaderboard[leaderboard.Root_Cause=='Out of Vocabulary (OOV)'].head(30)

,Source_Syllable,Moses_Output,True_Reference,Root_Cause,Error_Count
202,စ ကား,za- ga:,za- ga-,Out of Vocabulary (OOV),3
110,ခ နဲ,kha- ne:,ga- ne:,Out of Vocabulary (OOV),3
704,သက် က ရာဇ်,the' ka- ji',dha- ga- ji',Out of Vocabulary (OOV),2
644,ရို သေ,jou thei,jou dhei,Out of Vocabulary (OOV),2
240,စော် နံ,zo nan,so nan,Out of Vocabulary (OOV),2
201,စ ကား,za- ga-,za- ga:,Out of Vocabulary (OOV),2
190,ငေါ,ငေါ,ngo:,Out of Vocabulary (OOV),2
674,လှန်း,လှန်း,lhan:,Out of Vocabulary (OOV),2
166,ခြေ ချင်း,chi gyin:,chei gyin:,Out of Vocabulary (OOV),2
778,အဲ့,အဲ့,e.,Out of Vocabulary (OOV),2
13,ကန့် လန့်,kan. lan.,ga- lan.,Out of Vocabulary (OOV),2
317,တ ရား,ta- ja:,ta- ja-,Out of Vocabulary (OOV),2
615,ယဲ့,ယဲ့,je.,Out of Vocabulary (OOV),2
467,ပါ ဒ,ba da.,pa da.,Out of Vocabulary (OOV),2
599,မျက် နှာ,mje' nha-,mje' nha,Out of Vocabulary (OOV),2
657,ရှောင်း,ရှောင်း,shaun:,Out of Vocabulary (OOV),2
611,ယို့,ယို့,jou.,Out of Vocabulary (OOV),2
58,ကျို့,ကျို့,kyou.,Out of Vocabulary (OOV),2
577,ဘမ်း,ဘမ်း,ban:,Out of Vocabulary (OOV),1
576,ဘဒ်,ဘဒ်,ba',Out of Vocabulary (OOV),1
574,ဗျိုက်,ဗျိုက်,bjai',Out of Vocabulary (OOV),1
573,ဗိုဇ်,ဗိုဇ်,bai',Out of Vocabulary (OOV),1
572,ဗ ထက် ခြိုက်,ba. de' chai',ba. la- chai',Out of Vocabulary (OOV),1
600,မျက် နှာ ချေ,mje' nha- chi,mje' nha- chei,Out of Vocabulary (OOV),1
598,မျက် နှာ,mje' nha,mje nha-,Out of Vocabulary (OOV),1
595,မု လေး,ma- lei:,mja' le:,Out of Vocabulary (OOV),1
562,ဖြုန်း စပ်,bjoun: za',hpjoun: za',Out of Vocabulary (OOV),1
560,ဖျိုး,ဖျိုး,hpjou:,Out of Vocabulary (OOV),1
559,ဖျိုး,ဖျိုး,bjou:,Out of Vocabulary (OOV),1
578,ဘာ သာ,ba dha,hpa dha,Out of Vocabulary (OOV),1

In [9]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep 'ပစ် စည်း'

အာ မ ခံ ပစ် စည်း	a ma. gan |0-2| pji' si: |3-4| 	a ma. gan pji' si:
ပစ် စည်း ပစ် ယံ	pji' si: |0-1| pji' |2-2| jan |3-3| 	pji' si: pji' jan
ပင် ထွက် ပစ် စည်း	pin |0-0| dwe' pji' si: |1-3| 	pin dwe' pji' si:
အ သွင်း ပစ် စည်း	a- |0-0| thwin: |1-1| pji' si: |2-3| 	a- thwin: pji' si:
ကုန် ပစ် စည်း	koun |0-0| pji' si: |1-2| 	koun pji si:

In [10]:
!paste {file_train_src} {file_train_trg} | grep 'ပစ် စည်း'

သင် ချာ ပစ် စည်း	thin cha pji' si:
ဘေး ထွက် ပစ် စည်း	bei: dwe' pji' si:
လေ လွင့် ပစ် စည်း	lei lwin. pji' si:
ပစ် စည်း ပစ် စ ယ	pji' si: pji' sa- ja.
တွင်း ထွက် ပစ် စည်း	twin: dwe' pji' si:
မြေ ထွက် ပစ် စည်း	mjei dwe' pji' si:
ခန်း ဝင် ပစ် စည်း	khan: win pji' si:
ပစ် စည်း လေး ပါး	pji' si: lei: ba:
စစ် လက် နက် ပစ် စည်း	si' le' ne' pji' si:
ပျော် ဝင် ပစ် စည်း	pjo win pji' si:
ကြွေ ရည် သုတ် ပစ် စည်း	kywei jei dhou' pji' si:
အိမ် ထောင် ပစ် စည်း	ein daun pji' si:
ပစ် စည်း	pji' si:
ရှေး ဟောင်း ပစ် စည်း	shei: haun: pji' si:
ဘုံ ပစ် စည်း	boun pji' si:
ကား ပစ် စည်း	ka: pji' si:
စက် ပစ် စည်း	se' pji' si:
ရေ ထွက် ပစ် စည်း	jei dwe' pji' si:
ခိုး ရာ ပါ ပစ် စည်း	khou: ja ba pji' si:
ဇိမ် ခံ ပစ် စည်း	zein gan pji' si:
အ တွင်း ပစ် စည်း	a- twin: pji' si:
သက် သေ ခံ ပစ် စည်း	the' thei gan pji' si:
ပစ် စည်း မဲ့ လူ တန်း စား	pji' si: me: lu dan: za:
ကိုယ် ပိုင် ပစ် စည်း	kou bain pji' si:
ပစ် စည်း ရှိ	pji' si: shi.
ဘိုး ဘ ပိုင် ပစ် စည်း	bou: ba. bain pji' si:

In [11]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep 'အ ဘိ '

အ ဘိ ယာ စ က	a- |0-0| bi. |1-1| ja |2-2| za- ga. |3-4| 	a- bi. ja za- ka.
အ ဘိ ညာဉ်	a- |0-0| bi. |1-1| njin |2-2| 	a- bein njin

In [12]:
!paste {file_train_src} {file_train_trg} | grep 'အ ဘိ '

အ ဘိ ဓ ဇ မ ဟာ ရဋ် ဌ ဂု ရု	a- bi. da- za. ma- ha ra' hta. gu. ru.
အ ဘိ ဓမ် မာ	a- bi. da- ma
အ ဘိ ဓာန်	a- bei' dan
အ ဘိ သိက်	a- bei' thei'

In [13]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep 'အဲ့ '

ပုပ် အဲ့ အဲ့	pou' |0-0| အဲ့ |1-1| အဲ့ |2-2| 	pou' e. e.

In [14]:
!paste {file_train_src} {file_train_trg} | grep 'အဲ့ '

In [15]:
leaderboard[leaderboard.Root_Cause=='Reference Missing from Training Token'].head(30)

,Source_Syllable,Moses_Output,True_Reference,Root_Cause,Error_Count
508,ပျော်,pjo,bjo,Reference Missing from Training Token,2
31,ကုန်,koun,kou,Reference Missing from Training Token,2
605,မြီး,mji:,mhi:,Reference Missing from Training Token,2
567,ဖွင့်,hpwin.,hpwin,Reference Missing from Training Token,1
601,မြ,mja.,mja,Reference Missing from Training Token,1
597,မဲ့,me.,me,Reference Missing from Training Token,1
596,မောင်,maun,moun,Reference Missing from Training Token,1
570,ဖွေ,hpwei,bwei,Reference Missing from Training Token,1
550,ဖည်,hpe,be,Reference Missing from Training Token,1
584,မ,ma-,a',Reference Missing from Training Token,1
579,ဘိ,bi.,bein,Reference Missing from Training Token,1
478,ပီ,pi,pa-,Reference Missing from Training Token,1
503,ပျက်,pje',bje,Reference Missing from Training Token,1
500,ပေး,pei:,pjei:,Reference Missing from Training Token,1
486,ပုံ,poun,bou',Reference Missing from Training Token,1
462,ပန်း,pan:,pa-,Reference Missing from Training Token,1
534,ပြူ,pju,bju,Reference Missing from Training Token,1
493,ပေါက်,bau',pou',Reference Missing from Training Token,1
527,ပြိုင်,pjain,bjaun,Reference Missing from Training Token,1
34,ကုမ်,koun,goun,Reference Missing from Training Token,1
514,ပြည့်,pjei.,pji:,Reference Missing from Training Token,1
689,ဝိ,wi.,wei',Reference Missing from Training Token,1
749,အ,a-,a',Reference Missing from Training Token,1
747,ဟီး,hi:,he:,Reference Missing from Training Token,1
745,ဟင်,hin:,hin,Reference Missing from Training Token,1
736,သဲ,the:,thei:,Reference Missing from Training Token,1
768,အိပ်,ei',hei',Reference Missing from Training Token,1
15,ကန်,kan,ka,Reference Missing from Training Token,1
652,ရွား,jwa:,jwa,Reference Missing from Training Token,1
588,မ,ma.,ma:,Reference Missing from Training Token,1

In [16]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep 'မြီး'

လိပ် ကျောက် မြီး	lei' |0-0| kyau' |1-1| mji: |2-2| 	lei' kyau' mhi:
လှည်း နောက် မြီး	lhe: |0-0| nau' |1-1| mji: |2-2| 	lhe: nau' mi:
ကြွက် မြီး	kywe: mi: |0-1| 	kywe' mi:
ကိုင်း ဖြူ မြီး	kain: |0-0| hpju |1-1| mji: |2-2| 	kain: bju mi:
မြီး ထူး ရိုး	mji: |0-0| du: |1-1| jou: |2-2| 	mji: du: jou:
ဆောင်း မြီး နာ	hsaun: |0-0| mji: |1-1| na |2-2| 	hsaun: mji: na
လိပ် ကျောက် မြီး	lei' |0-0| kyau' |1-1| mji: |2-2| 	lei' kyau' mi:
အ မြီး စား ဖက် ခေါင်း စား ဖက်	a- mi: |0-1| sa: |2-2| hpe' |3-3| gaun: |4-4| za: |5-5| hpe' |6-6| 	a- mi: sa: be' gaun: sa: be'
ကျေး မြီး ဖို	kyei: mi: |0-1| hpou |2-2| 	kyei: mi: bou
ကင်း မြီး ကောက်	kin: mi: gau' |0-2| 	kin: mi: gau'
စစ် မြီး	si' |0-0| mji: |1-1| 	si' mhi:

In [17]:
!paste {file_train_src} {file_train_trg} | grep 'mhi:'

လင် မှီး	lin mhi:
သို မှီး	thou: mhi:
ရှာ မှီး	sha mhi:

In [18]:
leaderboard[leaderboard.Root_Cause=='Decoder Hallucination / Over-generalization'].head(30)

,Source_Syllable,Moses_Output,True_Reference,Root_Cause,Error_Count
414,ဒြေ,da- rei,da-,Decoder Hallucination / Over-generalization,1

In [19]:
!paste {file_train_src} {file_train_trg} | grep  'ဒြေ'

ဣန် ဒြေ ရှိ	ein da- rei shi.
ဣန် ဒြေ လုပ်	ein da- rei lou'
ဣန် ဒြေ မဲ့	ein da- rei me.
ဣန် ဒြေ	ein da- rei
စက် ခုန် ဒြေ	se' khoun da-
ဣန် ဒြေ ဆောင်	ein da- rei hsaun
ဣန် ဒြေ ဆည်	ein da- rei hse
ဣန် ဒြေ သမ် ပတ် တိ	ein da- rei than pa' ti.
ဣန် ဒြေ ပျက်	ein da- rei pje'
ရာ ဇိန် ဒြေ	ja zein da-
ဣန် ဒြေ ရ	ein da- rei ja.

In [20]:
!paste {file_test_src} {file_test_out} {file_test_ref} | grep 'ဒြေ'

ဣန် ဒြေ ကြီး	ein da- rei |0-1| gyi: |2-2| 	ein da- rei kyi:
ကာ ယိန် ဒြေ	ka |0-0| ယိန် |1-1| da- rei |2-2| 	ka jein da-